spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:asynchronous-checkout}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:asynchronous-checkout}
    password: ${DB_PASSWORD:asynchronous-checkout}
    hikari:
      maximum-pool-size: 200
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true