version: '3.8'

services:
  postgres:
    image: postgres:17.2-alpine
    container_name: virtual-account-service-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-virtual-account-service}
      POSTGRES_USER: ${POSTGRES_USER:-virtual-account-service}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-virtual-account-service}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U virtual-account-service -d virtual-account-service"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - virtual-account-service-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: virtual-account-service-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: ${DB_HOST:-postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-virtual-account-service}
      DB_USERNAME: ${DB_USERNAME:-virtual-account-service}
      DB_PASSWORD: ${DB_PASSWORD:-virtual-account-service}
    ports:
      - "8081:8080"
    networks:
      - virtual-account-service-network

volumes:
  postgres_data:

networks:
  virtual-account-service-network:
    driver: bridge

